# Guest OS timezone
timezone: Europe/London

# Are we need check box updates for every 'vagrant up'?
box_check_update: false

# Virtual machine name
machine_name: test-station

# Virtual machine IP
ip: 192.168.56.21

# Virtual machine CPU cores number
cpus: 1

# Virtual machine RAM
memory: 2048

# Domains
domains: {
    app: 'test-station.local'
}